### ISSUE TITLE
SecRequestManaget.SecGetAsync fails to retrieve the URL

### ISSUE THREAD

**Issue by nhirschey** [TimHanewich/SecuritiesExchangeCommission.Edgar#2]
Hi Tim,

Your set of Edgar libraries look really nice.

Do I need to do something special to get the library to work with Edgar? Your example code fails with an error indicating that possibly the server is not responding, but when I copy and paste that URL in the browser I get a result.

If you know the problem off the top of your head, that'd be great. Otherwise, I can investigate on my own time.

Thanks!

Here's some example code using a .NET interactive C# notebook:

```csharp
#r "nuget: SecuritiesExchangeCommission.Edgar"
#r "nuget: Xbrl"

using SecuritiesExchangeCommission.Edgar;
using Xbrl;
using System.IO;

//Search for a 10-K XBRL document and then download to a Stream
EdgarSearch es = await EdgarSearch.CreateAsync("INTC", "10-K");
EdgarSearchResult esr = es.GetFirstResultOfFilingType("10-K");
Stream s = await esr.DownloadXbrlDocumentAsync();

//Read the XBRL document
XbrlInstanceDocument doc = XbrlInstanceDocument.Create(s);

```

The error
```
System.Exception: Unable to get data for URL 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=INTC&type=10-K&owner=exclude&count=40'. Surpassed maximum try count of 10
   at SecuritiesExchangeCommission.Edgar.SecRequestManager.SecGetAsync(String url)
   at SecuritiesExchangeCommission.Edgar.EdgarSearch.CreateAsync(String stock_symbol, String filing_type, Nullable`1 prior_to, EdgarSearchOwnershipFilter ownership_filter, EdgarSearchResultsPerPage results_per_page)
   at Submission#12.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at SecuritiesExchangeCommission.Edgar.SecRequestManager.SecGetAsync(String url)
   at SecuritiesExchangeCommission.Edgar.EdgarSearch.CreateAsync(String stock_symbol, String filing_type, Nullable`1 prior_to, EdgarSearchOwnershipFilter ownership_filter, EdgarSearchResultsPerPage results_per_page)
   at Submission#12.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Comment by TimHanewich** [comment]
Hi @nhirschey, thanks for bringing this to my attention. And sorry for the late response.

Yes! Thanks for pointing this out. Before using this library, you must declare a User-Agent. The SEC requires all automated tools to declare who they are (name of your program or company). To set the user-agent that will be passed along and used in each SEC request, you can do it like this:

`SecuritiesExchangeCommission.Edgar.SecRequestManager.Instance.UserAgent = "MyCompany/4.1.0";`

I've added this important note to the readme [here](SecuritiesExchangeCommission.Edgar.SecRequestManager.Instance.UserAgent = "MyCompany/4.1.0";). I thought I had already but I suppose not! Thanks for bringing this up.

**Comment by nhirschey** [comment]
This works great. Thank you!
